name: MinecraftSSIVerification
version: 1.0.0
main: com.ssi.verification.SimpleSSIPlugin
api-version: 1.20
author: SSI_Metaverse
description: SSI verification plugin integrating with existing ACA-Py setup

commands:
  verify:
    description: Verify your identity using SSI credentials
    usage: /verify
    permission: ssi.verify
  ssiverify:
    description: Check player verification status
    usage: /ssiverify [player]
    permission: ssi.check

permissions:
  ssi.verify:
    description: Allows players to verify their identity
    default: true
  ssi.check:
    description: Allows checking verification status
    default: true
  ssi.admin:
    description: Admin permissions for SSI plugin
    default: op